### ISSUE TITLE
Make a website 

### ISSUE THREAD

**Issue by JeeheonKim** [Munro-L/I-spy-oT__cuHacking-2019#1]
**FOR VISUALIZING DATA**
- sign-in
- dashboard
- get data (control of
- History (e.g. 5 seconds interval)

**Comment by Akillarbee** [comment]
Activity log section

Location: 
-Home 
-Work 
-Other
 
Device section
list devices
Add devices button


- Drop down 

Warning Center:
Integration Section:


Check out https://ifttt.com/discover for ideas

**Comment by Akillarbee** [comment]
Warning section: 
Alerts for any oddities or items users have selected that they would not want to be shared. 
a button for selecting data that you want to receive alerts on ( Select Alerts)  (a place where you can select)

Safe Connection Section:

**Comment by Akillarbee** [comment]
dashboard mockup and Pitch 
https://docs.google.com/presentation/d/1qYwD1qnv4NxQTbIGYLQYjEhYV81n4G0xojpD_u_KjCY/edit?usp=sharing

**Comment by JeeheonKim** [comment]
canvasJS <- dashboard
https://canvasjs.com/samples/dashboards/

**Comment by Munro-L** [comment]
The new proxy server is up and serving connections. I placed a sample text file from tshark parser is in home directory (traffic.log). We're mostly interested in the outgoing POST data, and GET parameters, but we can add more if we have time.

**Comment by JeeheonKim** [comment]
http://34.73.52.137:8080/logTemps/getOne
get json and put data on the log file! 
Constant get request

**Comment by JeeheonKim** [comment]
// if the code is -1 -> just skip the data
// key: data, value: -1 -- dummy node
// key: data, value: dictionary (key: temp value:int) (key: timeStamp value:string(hour:minute:second[00:00:00]))

**Comment by JeeheonKim** [comment]
After everything is done,
- Hopefully, deploy it on Google Cloud Platform
- Domain!

**Comment by michaelPruss** [comment]
https://stackoverflow.com/questions/2591098/how-to-parse-json-in-java

**Comment by michaelPruss** [comment]
Alarm url:
/alarm
JSON: {"alarm": 0 or 1} 0 means no alarm, 1 means there is an alarm
