### ISSUE TITLE
IoT Device Server

### ISSUE THREAD

**Issue by Munro-L** [Munro-L/I-spy-oT__cuHacking-2019#4]
The actual target server for the IoT device. Only needs to take in data, and send back a confirmation that it was received.

**Comment by michaelPruss** [comment]
Need to install this package:
go get -u github.com/gorilla/mux

**Comment by michaelPruss** [comment]
$ virtualenv venv
$ source venv/bin/activate
$ pip install flask flask-jsonpify flask-sqlalchemy flask-restful
$ pip freeze
Run the above commands before executing new restAPI.py
